### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by leoxxx** [qq943260285/tampermonkey-recruitment-tool#14]
职位上的删除和查询图标都没了。左下角按钮只显示五个圈，图标没了。但原先屏蔽过的公司还会生效。
![QQ截图20230418105656](https://user-images.githubusercontent.com/5364709/232659846-409628f6-98e0-4684-ad60-95b7ae25de2e.png)

**Comment by qq943260285** [comment]
此回复表示我收到你的邮件了哦。   
    


    
        --
        
            
                小宇

**Comment by leoxxx** [comment]
~不知道啥情况，现在前程无忧又显示正常了，但猎聘问题依旧。~
现在问题依旧。

**Comment by leoxxx** [comment]
~现在彻底失效。~
手动黑名单漏了个逗号，现在半残状态。

**Comment by qq943260285** [comment]
此回复表示我收到你的邮件了哦。   
    


    
        --
        
            
                小宇

**Comment by leoxxx** [comment]
今天正常了。

**Comment by qq943260285** [comment]
此回复表示我收到你的邮件了哦。   
    


    
        --
        
            
                小宇
