### ISSUE TITLE
黑名单的意思是屏蔽公司的意思吗

### ISSUE THREAD

**Issue by paradox0618** [qq943260285/tampermonkey-recruitment-tool#16]
已star
是否会和boss内置的屏蔽公司冲突
![image](https://github.com/qq943260285/tampermonkey-recruitment-tool/assets/46587319/b778496a-d142-42b1-b16b-11c1b5af1948)

**Comment by qq943260285** [comment]
此回复表示我收到你的邮件了哦。   
    


    
        --
        
            
                小宇

**Comment by qq943260285** [comment]
> 已star 是否会和boss内置的屏蔽公司冲突 ![image](https://private-user-images.githubusercontent.com/46587319/304031393-b778496a-d142-42b1-b16b-11c1b5af1948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDMwNzEsIm5iZiI6MTcxODM0Mjc3MSwicGF0aCI6Ii80NjU4NzMxOS8zMDQwMzEzOTMtYjc3ODQ5NmEtZDE0Mi00MmIxLWIxNmItMTFjMWI1YWYxOTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OWY4MDRmMmRlZWYwOGM4MTE1NzgyYjgzOGIzN2Y2ODMwYjMxYjYzZGEwMTNiNzZlMDM0MWFiNjEyODk4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvcFJuBcOJZ7pKXBsk9dV5XreCRQbl5YqKcIYeaBV74)

没关系  独立
