### ISSUE TITLE
黑名单可以导入导出吗

### ISSUE THREAD

**Issue by ccjz286** [qq943260285/tampermonkey-recruitment-tool#3]
功能真实太棒了，

黑名单是存在哪呢了

**Comment by leoxxx** [comment]
tampermonkey里点击这个脚本，存储标签里的就是。

**Comment by YYY-LAKI** [comment]
> 功能真实太棒了,
> 
> 黑名单是存在哪呢了

tampermonkey的配置模式设为高级就能看到存储标签了
