### ISSUE TITLE
这个repo的代码怎么和greasyfork上的对不上？

### ISSUE THREAD

**Issue by sv158** [qq943260285/tampermonkey-recruitment-tool#4]
所以哪个是最新版？

另外zhipin.com的isRefresh要改了，不然HTMLtoList为空

**Comment by qq943260285** [comment]
@v3470 代码是一样的，greasyfork上是打包的，关于zhipin.com的HTMLtoList为空可以提供下地址吗？我看了下暂未发现问题。

**Comment by sv158** [comment]
@qq943260285 原来如此。HTMLtoList为空这个问题我也说不清楚情况，目前我用的脚本是自己改过isRefresh的版本，如果现在又没问题了的话那就没事了。
